### ISSUE TITLE
User can view header on homepage with typed.js

### ISSUE THREAD

**Issue by gdegas** [gdegas/gdegas.github.io#5]
## Tasks
- [x] npm install typed.js
- [x] Include script file that points to typed.js file in node modules
- [x] Follow code in setup from repo
